version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zxiat
    ports:
      - "3306:3306"
    volumes:
      - /Users/sunyulong/Desktop/docker/mysql/conf:/etc/mysql/conf.d
      - /Users/sunyulong/Desktop/docker/mysql/logs:/logs
      - /Users/sunyulong/Desktop/docker/mysql/data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /Users/sunyulong/Desktop/docker/mongo/data:/data/db

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
     - NEO4J_AUTH=neo4j/eszrdxtfc
    volumes:
      - /Users/sunyulong/Desktop/docker/neo4j/data:/data
      - /Users/sunyulong/Desktop/docker/neo4j/logs:/logs 
